apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-helloworld-2
  name: go-helloworld-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-helloworld-2
  template:
    metadata:
      labels:
        app: go-helloworld-2
    spec:
      containers:
      - image: ghcr.io/2022-4400-exp/4412-go-helloworld-2:b4ccd791eefafc010369a405b338e298e100636a
        name: go-helloworld-2